spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
##    url: jdbc:h2:file:~/.h2/test;Auto_Server=True;IgnoreCase=True;Mode=MySql
#    username: root
#    password: abc@!321
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.232.172.2:3306/msger?characterEncoding=utf-8&useSSL=false&allowMutiQueries=true
    username: root
    password: 123456

    name: test
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 'x'
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 60000

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.ant.msger.main.persistence.entity

# 打印sql
logging:
  level:
    com.ant.msger.main.persistence.dao: debug

server:
  port: 8000
  context-path: /
  tomcat:
    uri-encoding: UTF-8

